### ISSUE TITLE
any ideas to install from this ISO in a "networkless" computer ?

### ISSUE THREAD

**Issue by changchichung** [YasuhiroABE/ub2204-autoinstall-iso#6]
I try to install a new pc without network with this ISO , but installation failed when install packages 
the error message is "unable to locate package lubuntu-desktop"
I think it might be the network problem , any ideas/suggestions ?

**Comment by YasuhiroABE** [comment]
This project never asks you to install the lubuntu-desktop package, I'm not sure what happened.
You should show your differences against the procedure of document when asking a question.

I guess that you would like to install the lubuntu-desktop package for your PC and added the package name to the user-data file.

The canonical released the unattended/automatic desktop installer on github. -> https://github.com/canonical/autoinstall-desktop

It requires the server installer image and network access. 
Although I'm not sure why they didn't use the desktiop ISO image, it might mean to install the desktop packages without network access is too difficult.

It's possible to install the minimum ubuntu packages use this project's ISO image withouth network access, if you add the following lines to the user-data file.

```
  package_update: false
  package_upgrade: false
```

After booting the minimum ubuntu server on your PC, and if you can mount the lubuntu related deb package files, you might be possible to install desktop packages in an offline environment.
