### ISSUE TITLE
"make geniso" fails: Partition type '28732ac11ff8d211ba4b00a0c93ec93b' is out of range

### ISSUE THREAD

**Issue by dev8765** [YasuhiroABE/ub2204-autoinstall-iso#7]
Debian 10 Buster
===========

**export LANG=C**

**make geniso**
sudo env LANG=C xorriso -as mkisofs -volid MYUBISOIMG \
-output ubuntu-custom-autoinstaller.20231206.173939.iso \
-eltorito-boot boot/grub/i386-pc/eltorito.img \
-eltorito-catalog /boot.catalog -no-emul-boot \
-boot-load-size 4 -boot-info-table -eltorito-alt-boot \
-no-emul-boot -isohybrid-gpt-basdat \
-append_partition 2 28732ac11ff8d211ba4b00a0c93ec93b --interval:local_fs:4156048d-4166115d::'ubuntu-22.04.3-live-server-amd64.iso' \
-e '--interval:appended_partition_2_start_1782357s_size_8496d:all::' \
--grub2-mbr --interval:local_fs:0s-15s:zero_mbrpt,zero_gpt:'ubuntu-22.04.3-live-server-amd64.iso' \
"iso_root"
xorriso 1.5.0 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:ubuntu-custom-autoinstaller.20231206.173939.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 20.7g free
xorriso : FAILURE : -append_partition: **Partition type '28732ac11ff8d211ba4b00a0c93ec93b' is out of range** (0x00...0xff)
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'
make: *** [Makefile:69: geniso] Error 5

**Comment by YasuhiroABE** [comment]
Thank you for your information.

Reviewing the ChangeLog file of the xorriso, the xorriso version must be at least 1.5.2, I think.

    libisoburn-1.5.2.tar.gz  Sat Oct 26 2019
    ===============================================================================
    ...
    * Enabled GPT type GUIDs with -append_partition,
      -boot_image any iso_mbr_part_type=, and -as mkisofs -iso_mbr_part_type

Could you try to upgrade your xorriso version?

**Comment by dev8765** [comment]
I'm not happy with compiling, but maybe these is no other way for me

**Comment by YasuhiroABE** [comment]
If you can disable the secure boot and enable the legacy bios mode on your target machine, you can try to the instruction for APU/APU2 and old servers with the latest code.

*  [https://github.com/YasuhiroABE/ub2204-autoinstall-iso#support-for-apuapu2-or-other-old-machines](https://github.com/YasuhiroABE/ub2204-autoinstall-iso#support-for-apuapu2-or-other-old-machines)
    * Skip the line executing the sed command if you don't use the serial console.

The updated Makefile should work with the xorriso version, 1.5.0.

If you want to build an ISO image for GPT boot instead of the MBR boot, I think there is no stable instruction right now.

**Comment by dev8765** [comment]
Thank you for supporting.
Sadly I had no luck, my Linux environments are too old, "... -o loop: error", "... iso9660: error".
I try to update step by step from 18.04 -> 20.04 -> 22.04.
