### ISSUE TITLE
make download get "ERROR 404: Not Found" (

### ISSUE THREAD

**Issue by WadeTsai** [YasuhiroABE/ub2204-autoinstall-iso#8]
Please modify the "ISO_URLBASE" in Makefile.
Chnage "https://releases.ubuntu.com/22.04/" to "https://old-releases.ubuntu.com/releases/22.04/"

BTW, will you test the compatibility with 22.04.4? (https://releases.ubuntu.com/releases/22.04/ubuntu-22.04.4-live-server-amd64.iso)

**Comment by YasuhiroABE** [comment]
Thank you for your suggestion.
I've updated the ISO version to 22.04.4.
